export const memoryFormFactors = {
  "1": "OTHER",
  "2": "UNKNOWN",
  "3": "SIMM",
  "4": "SIP",
  "5": "CHIP",
  "6": "DIP",
  "7": "ZIP",
  "8": "PROPRIETARY_CARD",
  "9": "DIMM",
  "10": "TSOP",
  "11": "ROW_OF_CHIPS",
  "12": "RIMM",
  "13": "SODIMM",
  "14": "SRIMM",
  "15": "FB_DIMM",
  "16": "DIE",
  "17": "CAMM",
} as const;
